pimcore:
    properties:
        predefined:
            definitions:
                26edbc38-0327-4abf-b832-5920b805620e:
                    name: 'New Property'
                    description: null
                    key: new_key
                    type: text
                    data: null
                    config: null
                    ctype: document
                    inheritable: false
                    creationDate: 1733919421
                    modificationDate: 1733919421
