monolog:
    handlers:
        dev_logs:
            type: stream
            path: '%kernel.logs_dir%/custom_logs/dev_logs.log'
            level: debug 
            formatter: monolog.formatter.line
