pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    textmedia:
                        items: {  }
                        medias: {  }
                        name: textmedia
                        description: ''
                        group: ''
                        format: SOURCE
                        quality: 85
                        highResolution: null
                        preserveColor: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1734371874
                        creationDate: 1734371874
                        preserveAnimation: false
