_pimcore:
    resource: "@PimcoreCoreBundle/config/routing.yaml"

app:
    resource: "../src/Controller/"
    type: annotation

calculator_controllers:
    resource: '../src/Controller/Calculator'
    type: annotation

de:
  path: /de
  controller: App\Controller\ContentController::templateAction