type: tabpanel
items:
  - type: panel
    title: 'Aligning'
    items:
      - type: select
        label: 'Text Aligning'
        name: 'position'
        config:
          store:
            - [text-start, 'Left']
            - [text-center, 'Middle']
            - [text-end, 'Right']
      - type: select
        label: 'Space before'
        name: 'space-before'
        config:
          store:
            - [, 'None']
            - [mt-1, 'Very Small']
            - [mt-2, 'Small']
            - [mt-3, 'Medium']
            - [mt-4, 'Large']
            - [mt-5, 'Very Large']
      - type: select
        label: 'Space after'
        name: 'space-after'
        config:
          store:
            - [, 'None']
            - [mb-1, 'Very Small']
            - [mb-2, 'Small']
            - [mb-3, 'Medium']
            - [mb-4, 'Large']
            - [mb-5, 'Very Large']